# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  workflow_dispatch: # 添加手动触发支持
  release:
    types: [created, edited, published]

jobs:


  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - uses: pnpm/action-setup@v4.2.0
        with:
          version: latest
      - run: pnpm install
      - run: pnpm run build

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: ls -lah
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org/
      - uses: pnpm/action-setup@v4.2.0
        with:
          version: latest

      - run: pnpm lerna:publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  git-commit:
    needs: publish-npm
    runs-on: ubuntu-latest
    steps:
        - name: Git Auto Commit
          uses: stefanzweifel/git-auto-commit-action@v7.1.0
          with:
          # Commit message
            commit_message: "release !!"
          # Git branch name, where changes should be pushed too
            branch: ${{ github.ref_name }}  # 修复：使用当前分支而不是head_ref
          # Commit options
            commit_options: '--no-verify'
          # Name used for the commit user
            commit_user_name: 'releaase bot'
          # Email address used for the commit user
            commit_user_email: '41898282+github-actions[bot]@users.noreply.github.com'
          # Push options
            push_options: '--force'
        - run: echo "这个工作流是因为创建了Release而触发的！"
          


    
